# Generated by Django 4.1.3 on 2022-11-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_remarks_feedback_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhaar',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.CharField(max_length=100),
        ),
    ]
